version: "3.7"

# Common context for all services
x-common-dev: &common-tutorial
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - ./:/tutorial

services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8530:8529
    volumes:
      - db_container:/var/lib/arangodb3


  books:
    <<: *common-tutorial
    command: go run ./books
    environment:
      ARANGODB_DB: tutorial_books
      APP_PORT: 60001
    ports:
      - 60001:60001
    links:
      - arangodb

  holders:
    <<: *common-tutorial
    command: go run ./holders
    environment:
      ARANGODB_DB: tutorial_holders
      APP_PORT: 60001
    ports:
      - 60005:60001
    links:
      - arangodb

  graphql:
    <<: *common-tutorial
    command: go run ./graph_api
    environment:
      BOOKS_SERVICE: books:60001
      HOLDERS_SERVICE: holders:60001
      GRAPH_API_PORT: 80
    ports:
      - 8080:80
    links:
      - books
      - holders

volumes:
  db_container: